<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jstimezonedetect/1.0.4/jstz.min.js"></script>

<div data-role="page" class="safetext-page safetext-messages folder_<?php echo $this->getValue('folder'); ?>" data-title="<?php echo ucfirst($this->getValue('folder')); ?>">
		
		<?php echo $this->render('webclient/_leftpanel.phtml'); ?>
		<?php echo $this->render('webclient/_header.phtml'); ?>
	
	    <div data-role="content" class="safetext-content" data-theme="a">
	    	
		    <div class="safetext-client-grid">
		    	<!-- Left-hand Folder Column -->
			    <div class="safetext-block-a">
			    	<div class="ui-body ui-body-d">
					    <?php echo $this->render('webclient/_foldermenu.phtml'); ?>
					</div>
			    </div>
			    
			    <!-- Main Content Column -->
			    <div class="safetext-block-b">
			    	<div class="ui-body ui-body-d">
				    	<div class="ui-grid-b safetext-mobile-hidden">
						    <div class="ui-block-a"><a href="/webclient/messages" class="ui-shadow ui-btn ui-corner-all ui-btn-icon-left ui-icon-mail ui-btn-active">Messages</a></div>
						    <div class="ui-block-b"><a href="/webclient/contacts" class="ui-btn ui-corner-all ui-btn-icon-left ui-icon-user">Contacts</a></div>
						    <div class="ui-block-c"><a href="/settings" class="ui-btn ui-corner-all ui-btn-icon-left ui-icon-gear">Settings</a></div>
						</div>
						
						<div class="msgListWrapper">
						    <ul data-role="listview" data-filter="true" data-split-icon="<?php if ($this->getValue('folder')=='drafts') echo 'gear'; else echo 'delete'; ?>" data-inset="true">
						    	<?php foreach ($this->getValue($this->getValue('folder')) as $this_message) : 
							    	// get sender label
							    	if ($this_message->sender === $this->getValue('user')->id) {
							    		$sender = 'Me';
							    	} else {
							    		$contact = $this->getValue('contacts')->find('contact_user_id', $this_message->sender);
							    		if ($contact instanceof SafetextContact) $sender = $contact->label();
							    			else $sender = 'Unknown';
							    	}
							    	
							    	// get recipient label
							    	if ($this_message->recipient === $this->getValue('user')->id) {
							    		$recipient = 'Me';
							    	} else {
							    		$contact = $this->getValue('contacts')->find('contact_user_id', $this_message->recipient );
							    		if ($contact instanceof SafetextContact) $recipient = $contact->label();
							    			else $recipient = 'Unknown';
							    	}
							    	
							    	// get time to expire
							    	$secsLeft = strtotime($this_message->expire_date) - time();
							    	if ($secsLeft < 0) $secsLeft = 0;
							    	$minsLeft = round($secsLeft /60, 0, PHP_ROUND_HALF_DOWN);
							    	$hrsLeft = round($minsLeft /60, 0, PHP_ROUND_HALF_DOWN);
							    	
							    	if ($hrsLeft < 1) {
							    		$timeLeft = $minsLeft . ' ' . $this->t('min');
							    		if ($minsLeft > 1 || $minsLeft === 0) $timeLeft .= 's';
							    	} else {
							    		$timeLeft = $hrsLeft . ' ' . $this->t('hr');
							    		if ($hrsLeft > 1) $timeLeft .= 's';
							    	}
						    	?>
						    		<li>
									<a href="#" onclick="timezone(<?php echo $contact->contact_user_id;?>);" class="message">
						    			<?php if ($this_message->image_name != ''): ?>
						    				<img src="/assets/images/users/<?php echo $this_message->image_name; ?>-s.jpg" />
						    			<?php endif; ?>
						    			<?php if ($this->getValue('folder') !== 'sent' && $this->getValue('folder') !== 'drafts' && $this_message->is_read === '0') : ?>
						    				<p style="white-space:normal;"><strong><em><?php echo $sender; ?></em> <?php echo $this->t('to'); ?> <em><?php echo $recipient; ?></em></strong></p>
						    			<?php else: ?>
						    				<p style="white-space:normal;"><em><?php echo $sender; ?></em> <?php echo $this->t('to'); ?> <em><?php echo $recipient; ?></em></p>
						    			<?php endif; ?>
						    			<p><?php echo $this_message->content; ?></p>
						    			<p style="font-size:.68em;">sent <?php echo $this_message->sent_date; ?></p>
						    			<p class="ui-li-aside"><strong><?php echo $this->t('time left'); ?>: <?php echo $timeLeft; ?></strong></p></a>
						    			<a href="#" data-safetext-message-id="<?php echo $this_message->id; ?>" class="<?php if ($this->getValue('folder')=='drafts') echo 'safetext-editdraft-button'; else echo 'safetext-delete-button'; ?>"></a>
						    		</li>
						    	<?php endforeach; ?>
								
								<?php foreach($this->getValue('groupmessages') as $this_group_message) {
								
								if($this_group_message['group_name'] !="") {
								if ($this_group_message['sender_id'] === $this->getValue('user')->id) {
							    	$sender_name = 'Me';
							    }
								else {
									$sender_name = $this_group_message['sender_name'];
								}
								
								// get time to expire
							    	$secsLeft = strtotime($this_group_message['expire_date']) - time();
							    	if ($secsLeft < 0) $secsLeft = 0;
							    	$minsLeft = round($secsLeft /60, 0, PHP_ROUND_HALF_DOWN);
							    	$hrsLeft = round($minsLeft /60, 0, PHP_ROUND_HALF_DOWN);
							    	
							    	if ($hrsLeft < 1) {
							    		$timeLeft = $minsLeft . ' ' . $this->t('min');
							    		if ($minsLeft > 1 || $minsLeft === 0) $timeLeft .= 's';
							    	} else {
							    		$timeLeft = $hrsLeft . ' ' . $this->t('hr');
							    		if ($hrsLeft > 1) $timeLeft .= 's';
							    	}
								?>
								<li>
								<?php
									echo $url = "/webclient/groupconversation/group_id/".$this_group_message['group_id']."/participants_id/".$this_group_message['participants_id'];
								?>
								<a href="#" onclick="group_timezone(<?php echo $url;?>);" class="message">
								<p style="white-space:normal;"><strong><em><?php echo $sender_name; ?> To <?php echo $this_group_message['group_name']; ?></em></strong></p>
								<p><?php echo $this_group_message['content']; ?></p>
								<p>sent <?php echo $this_group_message['sent_date']; ?></p>
								<p class="ui-li-aside"><strong><?php echo $this->t('time left'); ?>: <?php echo $timeLeft; ?></strong></p>
								<a href="#" data-safetext-message-id="<?php echo $this_group_message->id; ?>" class="<?php echo 'safetext-delete-button'; ?>"></a>
								</a>
								</li>
								<?php }
								}?>
								
							</ul>
						</div>
						    
			    	</div>
			    </div>

			</div>
	    
	    </div><!-- /content -->
	    
	    
	    <?php if ($this->getValue('folder')=='drafts') : ?>
	    	<!-- edit draft popup -->
			<div data-role="popup" class="safetext-editdraft-menu" data-theme="b">
				<a href="#" data-rel="back" class="ui-btn ui-corner-all ui-shadow ui-btn-a ui-icon-delete ui-btn-icon-notext ui-btn-right">Close</a>
                <ul data-role="listview" data-inset="true" style="min-width:210px;">
                    <li data-role="list-divider"><?php echo $this->t('Edit Draft'); ?></li>
                    <li data-icon="carat-r"><a href="#" class="safetext-send-draft-button" data-safetext-sendmessage-id=""><?php echo $this->t('Send'); ?></a></li>
                    <li data-icon="delete"><a href="#" class="safetext-confirm-delete-button" data-safetext-deletemessage-id=""><?php echo $this->t('Delete Permanently'); ?></a></li>
                </ul>
            </div>
	    
			<!-- // edit draft popup -->
	    <?php else : ?>
		    <!-- delete message popup -->
				<div class="safetext-confirm-delete-popup" data-role="popup" data-overlay-theme="b" data-theme="b" data-dismissible="false" style="max-width:400px;">
			    	<a href="#" data-rel="back" class="ui-btn ui-corner-all ui-shadow ui-btn-a ui-icon-delete ui-btn-icon-notext ui-btn-right">Close</a>
			        <div data-role="header" data-theme="a">
			            <h1><?php echo $this->t('Delete Message'); ?>?</h1>
			        </div>
			        <div role="main" class="ui-content">
			            <h3 class="ui-title"><?php echo $this->t('Confirm delete'); ?></h3>
			            <p><?php echo $this->t('This message will be permanently deleted for all participants'); ?>. <?php echo $this->t('This action is not reversible'); ?>.</p>
			            <fieldset class="ui-grid-a">
				            <div class="ui-block-a"><a href="#" class="ui-btn ui-corner-all ui-shadow ui-btn-b" data-rel="back">Cancel</a></div>
				            <div class="ui-block-b"><a href="#" class="ui-btn ui-corner-all ui-shadow ui-btn-b safetext-confirm-delete-button" 
				                data-safetext-deletemessage-id=""
								data-rel="back" data-transition="flow"><?php echo $this->t('Delete'); ?></a></div>
			            </fieldset>
			        </div>
			    </div>
		    <!-- /delete message popup -->
	    <?php endif; ?>
	    
	
	<?php echo $this->render('webclient/_footer.phtml'); ?>
		
</div> <!--/page-->
<script type="text/javascript">
function timezone(cont_id) {

	var tz = jstz.determine(); 
	var timezone1 = tz.name(); 
	//var timezone = timezone1.replace("/","-");	
	var timezone2 = timezone1.split("/");
	var timezone = timezone2[0]+"-"+timezone2[1];
	//var contact_id1 = $(this).attr("id");
	//var contact_id2 = contact_id1.split("_");
	var contact = cont_id;
	
	//alert(contact);
	var url = "/webclient/conversation/contact/"+contact+"/timezone/"+timezone;
	window.location.href = url;
	
}

function group_timezone(redirect_url) {

	alert(1);
	var tz = jstz.determine(); 
	var timezone1 = tz.name(); 
	//var timezone = timezone1.replace("/","-");	
	var timezone2 = timezone1.split("/");
	var timezone = timezone2[0]+"-"+timezone2[1];
	//var contact_id1 = $(this).attr("id");
	//var contact_id2 = contact_id1.split("_");
	
	
	//alert(contact);
	var url = redirect_url+"/timezone/"+timezone;
	window.location.href = url;
	
}
</script>
