<div data-role="page" class="safetext-page safetext-settings" data-title="<?php echo $this->t('Settings'); ?>">
		
		<?php echo $this->render('webclient/_leftpanel.phtml'); ?>
		<?php echo $this->render('webclient/_header.phtml'); ?>
	
	    <div data-role="content" class="safetext-content" data-theme="a">
	    	
            <div class="ui-corner-all safetext-rounded-corners">
                  <div class="ui-bar ui-bar-a">
                    <h3><?php echo $this->t('Settings'); ?></h3>
                  </div>
                  <div class="ui-body ui-body-b">
                        <form class="safetext-settings-form">
                            <ul data-role="listview" data-inset="true" data-theme="a">
                            	<li data-role="list-divider"><?php echo $this->t('Account'); ?></li>
                                <li class="ui-field-contain">
                                    <label for="username"><?php echo $this->t('Username'); ?>:</label>
                                    <input type="text" name="username" value="<?php echo $this->getValue('user')->username; ?>" data-clear-btn="true">
                                </li>
                                <li class="ui-field-contain">
                                    <label for="email"><?php echo $this->t('Email'); ?>:</label>
                                    <input type="text" name="email" value="<?php echo $this->getValue('user')->email; ?>" data-clear-btn="true">
                                </li>
                                <li class="ui-field-contain">
                                    <label for="pass"><?php echo $this->t('Change Password'); ?>: <a href="#safetext-password-info" data-rel="popup" data-transition="pop" class="safetext-tooltip-btn ui-btn ui-alt-icon ui-nodisc-icon ui-btn-inline ui-icon-info ui-btn-icon-notext ui-corner-all">Info</a></label>
                                    <input type="text" name="pass" value="" data-clear-btn="true">
                                    <div data-role="popup" id="safetext-password-info" class="ui-content" data-theme="a" style="max-width:350px;">
								      <a href="#" data-rel="back" class="ui-btn ui-corner-all ui-shadow ui-btn-a ui-icon-delete ui-btn-icon-notext ui-btn-right">Close</a>
								      <p><?php echo $this->t('Last updated'); ?>: <?php echo date('M jS, Y', strtotime($this->getValue('user')->last_pass_update)); ?></p>
								    </div>
                                </li>
                                
                                <li class="ui-field-contain">
                                    <label for="firstname"><?php echo $this->t('First Name'); ?>:</label>
                                    <input type="text" name="firstname" value="<?php echo $this->getValue('user')->firstname; ?>" data-clear-btn="true">
                                </li>
                                <li class="ui-field-contain">
                                    <label for="lastname"><?php echo $this->t('Last Name'); ?>:</label>
                                    <input type="text" name="lastname" value="<?php echo $this->getValue('user')->lastname; ?>" data-clear-btn="true">
                                </li>
                                <li class="ui-field-contain">
                                    <label for="phone"><?php echo $this->t('Phone'); ?>:</label>
                                    <input type="text" name="phone" value="<?php echo $this->getValue('user')->phone; ?>" data-clear-btn="true">
                                </li>
                                <li class="ui-field-contain">
                                    <label for="notifications_on"><?php echo $this->t('Notifications'); ?>: <a href="#safetext-notifications-info" data-rel="popup" data-transition="pop" class="safetext-tooltip-btn ui-btn ui-alt-icon ui-nodisc-icon ui-btn-inline ui-icon-info ui-btn-icon-notext ui-corner-all">Info</a></label>
									<select name="notifications_on" data-role="slider">
						                <option value="0"><?php echo $this->t('No'); ?></option>
						                <option value="1"<?php if ($this->getValue('user')->notifications_on === '1') echo ' selected'; ?>><?php echo $this->t('Yes'); ?></option>
						            </select>
						            <div data-role="popup" id="safetext-notifications-info" class="ui-content" data-theme="a" style="max-width:350px;">
								      <a href="#" data-rel="back" class="ui-btn ui-corner-all ui-shadow ui-btn-a ui-icon-delete ui-btn-icon-notext ui-btn-right">Close</a>
								      <p><?php echo $this->t('If enabled, activity notifications will be sent to your device'); ?></p>
								    </div>
                                </li>
                                <li class="ui-field-contain">
                                    <label for="whitelist_only"><?php echo $this->t('Whitelist Only'); ?>: <a href="#safetext-whitelist-info" data-rel="popup" data-transition="pop" class="safetext-tooltip-btn ui-btn ui-alt-icon ui-nodisc-icon ui-btn-inline ui-icon-info ui-btn-icon-notext ui-corner-all">Info</a></label>
									<select name="whitelist_only" data-role="slider">
						                <option value="0"><?php echo $this->t('No'); ?></option>
						                <option value="1"<?php if ($this->getValue('user')->whitelist_only === '1') echo ' selected'; ?>><?php echo $this->t('Yes'); ?></option>
						            </select>
						            <div data-role="popup" id="safetext-whitelist-info" class="ui-content" data-theme="a" style="max-width:350px;">
								      <a href="#" data-rel="back" class="ui-btn ui-corner-all ui-shadow ui-btn-a ui-icon-delete ui-btn-icon-notext ui-btn-right">Close</a>
								      <p><?php echo $this->t('If enabled, only users from your whitelist can see and contact you'); ?></p>
								    </div>
                                </li>
                                <li class="ui-field-contain">
                                    <label for="enable_panic"><?php echo $this->t('Panic Button'); ?>:</label>
									<select name="enable_panic" data-role="slider">
						                <option value="0"><?php echo $this->t('No'); ?></option>
						                <option value="1"<?php if ($this->getValue('user')->enable_panic === '1') echo ' selected'; ?>><?php echo $this->t('Yes'); ?></option>
						            </select>
                                </li>
                                <li>
                                	<input type="hidden" name="language" value="en" />
                                	<button class="ui-btn ui-corner-all ui-btn-a safetext-apply-button ui-icon-check ui-btn-icon-left">Apply</button>
                                </li>
                                
                                
                                <li data-role="list-divider"><?php echo $this->t('Membership Status'); ?></li>
                                <li data-icon="gear">
                               		<a href="#" class="safetext-membership-options-button">
                                        <h2><?php if ($this->getValue('user')->subscription_level < 1) echo $this->t('Not Active'); else echo $this->t('Active'); ?></h2>
                                        <p style="white-space: normal;"><strong><?php if ($this->getValue('user')->subscription_level < 1) echo $this->t('Subscribe today to activate your account and enable message sending'); else if ($this->getValue('user')->subscription_recurs === '1') echo $this->t('Auto-renews on') . ' ' . date('M jS, Y', strtotime($this->getValue('user')->subscription_expires)); else echo $this->t('Expires on') . ' ' . date('M jS, Y', strtotime($this->getValue('user')->subscription_expires)); ?></strong></p>
                                    </a>
                                </li>
                                
                                <?php if (sizeof($this->getValue('devices')) > 0): ?>
                              		<li data-role="list-divider"><?php echo $this->t('Registered Devices'); ?></li>
							  		<?php foreach ($this->getValue('devices') as $this_device) : ?>
	                               <li id="safetext-devicelisting-<?php echo $this_device->id; ?>" data-icon="delete" data-safetext-device-token="<?php echo $this_device->token; ?>">
	                               		<a href="#" class="safetext-delete-button">
	                                        <h2><?php echo $this_device->description; ?></h2>
	                                        <p><strong><?php echo $this->t('Signature'); ?>:</strong> <?php echo $this_device->signature; ?></p>
											<?php if ($this_device->is_initialized != '1') echo '<p> &middot; <em>' . $this->t('Not yet synchronized') . '</em></p>'; ?>
										</a>
	                                </li>
	                            <?php endforeach; ?>
                                
                                <?php endif; ?>
                            </ul>
                        </form>
                   </div>
            </div>

	    	
	    </div><!-- /content -->
	
	<!-- delete message popup -->
		<div class="safetext-confirm-delete-popup" data-role="popup" data-overlay-theme="b" data-theme="b" data-dismissible="false" style="max-width:400px;">
	    	<a href="#" data-rel="back" class="ui-btn ui-corner-all ui-shadow ui-btn-a ui-icon-delete ui-btn-icon-notext ui-btn-right">Close</a>
	        <div data-role="header" data-theme="a">
	            <h1><?php echo $this->t('Unregister Device'); ?>?</h1>
	        </div>
	        <div role="main" class="ui-content">
	            <h3 class="ui-title"><?php echo $this->t('Please confirm'); ?></h3>
	            <p><?php echo $this->t('This device will be unregistered and any on-server sync data will be removed'); ?>.</p>
	            <fieldset class="ui-grid-a">
		            <div class="ui-block-a"><a href="#" class="ui-btn ui-corner-all ui-shadow ui-btn-b" data-rel="back">Cancel</a></div>
		            <div class="ui-block-b"><a href="#" class="ui-btn ui-corner-all ui-shadow ui-btn-b safetext-confirm-delete-button" 
		                data-safetext-deletedevice-token=""
						data-rel="back" data-transition="flow"><?php echo $this->t('Unregister'); ?></a></div>
	            </fieldset>
	        </div>
	    </div>
    <!-- /delete message popup -->
    
    <!-- subscription options popup -->
    	<div data-role="popup" class="safetext-subscription-options-menu" data-theme="b">
			<a href="#" data-rel="back" class="ui-btn ui-corner-all ui-shadow ui-btn-a ui-icon-delete ui-btn-icon-notext ui-btn-right">Close</a>
            <ul data-role="listview" data-inset="true" style="min-width:210px;">
                <li data-role="list-divider"><?php echo $this->t('Update Subscription'); ?></li>
                <?php if ($this->getValue('user')->subscription_level < 1) : ?>
                	<li data-icon="carat-r"><a href="/settings/subscribe" class="safetext-subscribe-button" data-safetext-sendmessage-id=""><?php echo $this->t('Subscribe'); ?></a></li>
                <?php elseif ($this->getValue('user')->subscription_recurs === '1') : ?>
                	<li data-icon="carat-r"><a href="#" class="safetext-disable-autorenew-button" data-safetext-sendmessage-id=""><?php echo $this->t('Disable Auto-Renew'); ?></a></li>
                <?php else: ?>
                	<li data-icon="carat-r"><a href="/settings/subscribe" class="safetext-subscribe-button" data-safetext-sendmessage-id=""><?php echo $this->t('Extend'); ?></a></li>
                <?php endif; ?>
                <li data-icon="carat-r"><a href="#" class="safetext-paymenthistory-button" data-safetext-deletemessage-id=""><?php echo $this->t('Payment History'); ?></a></li>
                <li data-icon="carat-r"><a href="#" class="safetext-updatecard-button" data-safetext-deletemessage-id=""><?php echo $this->t('Change Payment Card'); ?></a></li>
            </ul>
        </div>
	<!-- /subscription options popup -->
	    
	<?php echo $this->render('webclient/_footer.phtml'); ?>
		
</div> <!--/page-->