<style>
.safetext-message-settings-popup2 {height:300px;width:400px;overflow:auto}
@media only screen and (min-width: 480px) and (max-width: 767px) {
 .safetext-message-settings-popup2 {height:400px;width:400px;overflow:auto}
}
@media only screen and (max-width: 767px) {
 .safetext-message-settings-popup2 {height:280px;width:284px}
}
.dtpicker-components {
overflow: hidden;
margin: 1em 1em;
font-size: 1.4em;
}
.dtpicker-components .dtpicker-compOutline {
display: inline-block;
float: left;
}
.dtpicker-components .dtpicker-comp {
margin: 2%;
text-align: center;
}
.dtpicker-components .dtpicker-compButton {
background: #FFFFFF;
font-size: 140%;
cursor: pointer;
}
.dtpicker-components .dtpicker-compButtonEnable {
opacity: 1;
}
.dtpicker-components .dtpicker-compValue {
margin: 0em 0em;
width: 100%;
border: none;
font-size: 71%;
-webkit-appearance: none;
}
.dtpicker-comp2 {
width: 50%;
}
.dtpicker-components .dtpicker-comp > * {
display: block;
height: 30px;
color: #2980B9;
text-align: center;
line-height: 30px;
}
.dtpicker-components .dtpicker-comp > *:hover {
color: #2980B9;
}


.safetext-bubble {height:250px;width:300px;overflow:auto}
.safetext-bubble li{list-style:none; border-bottom:1px solid dashed; padding:0 0 10px 0; cursor:pointer}


.safetext-language {width:300px;overflow:auto}
.safetext-language li{list-style:none; border-bottom:1px solid dashed; padding:0 0 10px 0; cursor:pointer}

.safetext-delay {width:300px;overflow:auto}
.safetext-delay li{list-style:none; border-bottom:1px solid dashed; padding:0 0 10px 0; cursor:pointer}
</style>
<div data-role="page" class="safetext-page safetext-settings" data-title="<?php echo $this->t('Settings'); ?>">
		<div class="heaver-img"></div>	
		<?php echo $this->render('webclient/_leftpanel.phtml'); ?>
		<?php echo $this->render('webclient/_header.phtml'); ?>
	
	    <div data-role="content" class="safetext-content" data-theme="a">
         <div class="safetext-client-grid">
		    	<!-- Left-hand Folder Column -->
			    <div class="safetext-block-a">
			    	<div class="ui-body ui-body-d">
					    <?php echo $this->render('webclient/_foldermenu.phtml'); ?>
					</div>
			    </div>	    	
            <div class="safetext-block-b">

		<div class="ui-grid-a safetext-mobile-hidden">
			<div class="ui-block-a" style="width:99%;float:left;clear:none"><a href="" class="ui-btn ui-corner-all ui-btn-icon-left ui-icon-gear ui-btn-active">Settings</a></div>
			
		</div>
                  
                  <div class="settingWrapper">
                        <form class="safetext-settings-form" style="margin:14px;width:97%">
                        <input type="hidden" name="user_id" id="user_id" value="<?php echo $this->getValue('user')->id; ?>">
                            <ul data-role="listview" data-inset="true" data-theme="a">
                            	<li data-role="list-divider" class="ui-li-divider ui-bar-inherit ui-first-child"><?php echo $this->t('Settings'); ?></li>
                                <li class="ui-field-contain w50 fl">
                                    <label for="username"><?php echo $this->t('Username'); ?>:</label>
                                    <input type="text" name="username" value="<?php echo $this->getValue('user')->username; ?>" data-clear-btn="true">
                                </li>
								
                                <li class="ui-field-contain w50 fl">
                                    <label for="email"><?php echo $this->t('Email'); ?>:</label>
                                    <input type="text" name="email" value="<?php echo $this->getValue('user')->email; ?>" data-clear-btn="true">
                                </li>
								
                                <li class="ui-field-contain w50 fullbtn">
                                    <label for="pass"><?php echo $this->t('Change Password'); ?>: <a href="#safetext-password-info" data-rel="popup" data-transition="pop" class="safetext-tooltip-btn ui-btn ui-alt-icon ui-nodisc-icon ui-btn-inline ui-icon-info ui-btn-icon-notext ui-corner-all">Info</a></label>
                                    <input type="password" name="pass" value="" data-clear-btn="true">
                                    <div data-role="popup" id="safetext-password-info" class="ui-content" data-theme="a" style="max-width:350px;">
								      <a href="#" data-rel="back" class="ui-btn ui-corner-all ui-shadow ui-btn-a ui-icon-delete ui-btn-icon-notext ui-btn-right">Close</a>
								      <p><?php echo $this->t('Last updated'); ?>: <?php echo date('M jS, Y', strtotime($this->getValue('user')->last_pass_update)); ?></p>
								    </div>
                                </li>
                                <!--
                                <li class="ui-field-contain w50 fl">
                                    <label for="pass"><?php echo $this->t('Security Code'); ?>: <a href="#safetext-code-info" data-rel="popup" data-transition="pop" class="safetext-tooltip-btn ui-btn ui-alt-icon ui-nodisc-icon ui-btn-inline ui-icon-info ui-btn-icon-notext ui-corner-all">Info</a></label>
                                    <input type="text" disabled value="<?php echo MD5('seCURityCode' . $this->getValue('user')->id); ?>">
                                    <div data-role="popup" id="safetext-code-info" class="ui-content" data-theme="a" style="max-width:350px;">
								      <a href="#" data-rel="back" class="ui-btn ui-corner-all ui-shadow ui-btn-a ui-icon-delete ui-btn-icon-notext ui-btn-right">Close</a>					  <p>Use this code to authenticate your account for third-party applications. To use, copy and paste into the "Security Code" field of the application requesting Safe-Text access. This is a hashcode based on your user ID can cannot be changed.</p>
								    </div>
                                </li>-->
                                
                                <li class="ui-field-contain w50 fl">
                                    <label for="firstname"><?php echo $this->t('First Name'); ?>:</label>
                                    <input type="text" name="firstname" value="<?php echo $this->getValue('user')->firstname; ?>" data-clear-btn="true">
                                </li>
                                <li class="ui-field-contain w50 fl">
                                    <label for="lastname"><?php echo $this->t('Last Name'); ?>:</label>
                                    <input type="text" name="lastname" value="<?php echo $this->getValue('user')->lastname; ?>" data-clear-btn="true">
                                </li>
								<!--
                                <li class="ui-field-contain w50 fl">
                                    <label for="phone"><?php echo $this->t('Phone'); ?>:</label>
                                    <input type="text" name="phone" value="<?php echo $this->getValue('user')->phone; ?>" data-clear-btn="true">
                                </li>
								-->
                                <li class="ui-field-contain w50 fl">
                                    <label for="notifications_on"><?php echo $this->t('Notifications'); ?>: <a href="#safetext-notifications-info" data-rel="popup" data-transition="pop" class="safetext-tooltip-btn ui-btn ui-alt-icon ui-nodisc-icon ui-btn-inline ui-icon-info ui-btn-icon-notext ui-corner-all">Info</a></label>
									<select name="notifications_on" data-role="slider">
						                <option value="0"><?php echo $this->t('No'); ?></option>
						                <option value="1"<?php if ($this->getValue('user')->notifications_on === '1') echo ' selected'; ?>><?php echo $this->t('Yes'); ?></option>
						            </select>
						            <div data-role="popup" id="safetext-notifications-info" class="ui-content" data-theme="a" style="max-width:350px;">
								      <a href="#" data-rel="back" class="ui-btn ui-corner-all ui-shadow ui-btn-a ui-icon-delete ui-btn-icon-notext ui-btn-right">Close</a>
								      <p><?php echo $this->t('If enabled, activity notifications will be sent to your device(s).'); ?></p>
								    </div>
                                </li>
								<!--
                                <li class="ui-field-contain w50 fl">
                                    <label for="whitelist_only"><?php echo $this->t('Whitelist Only'); ?>: <a href="#safetext-whitelist-info" data-rel="popup" data-transition="pop" class="safetext-tooltip-btn ui-btn ui-alt-icon ui-nodisc-icon ui-btn-inline ui-icon-info ui-btn-icon-notext ui-corner-all">Info</a></label>
									<select name="whitelist_only" data-role="slider">
						                <option value="0"><?php echo $this->t('No'); ?></option>
						                <option value="1"<?php if ($this->getValue('user')->whitelist_only === '1') echo ' selected'; ?>><?php echo $this->t('Yes'); ?></option>
						            </select>
						            <div data-role="popup" id="safetext-whitelist-info" class="ui-content" data-theme="a" style="max-width:350px;">
								      <a href="#" data-rel="back" class="ui-btn ui-corner-all ui-shadow ui-btn-a ui-icon-delete ui-btn-icon-notext ui-btn-right">Close</a>
								      <p><?php echo $this->t('If enabled, only users from your whitelist can see and contact you'); ?></p>
								    </div>
                                </li>
								-->
                                <li class="ui-field-contain w50 fl">
                                    <label for="enable_panic"><?php echo $this->t('Panic Button'); ?>:</label>
									<select name="enable_panic" data-role="slider">
						                <option value="0"><?php echo $this->t('No'); ?></option>
						                <option value="1"<?php if ($this->getValue('user')->enable_panic === '1') echo ' selected'; ?>><?php echo $this->t('Yes'); ?></option>
						            </select>
                                </li>
                                <li class="clearDivider fullbtn" style="height:auto">
                                	<label for="enable_panic">Notes:</label>
                                	<textarea name="notes" id="notes"><?php echo $this->getValue('notes'); ?></textarea>
                                </li>
								<!--
                                <li class="clearDivider fullbtn">
                                	<input type="hidden" name="language" value="en" />
                                	<button class="fullButton safetext-settings-apply">Apply</button>
                                </li>
								-->
                                <li class="clearDivider fullbtn">
                                <button class="msg_setting_button">Message Default Time ( <span id="lifetime_value">
                                <?php 
                                if($this->getValue('lifetime')!="") 
                                { 
                                	$hour = intval($this->getValue('lifetime')/60);
                                	$minute = fmod($this->getValue('lifetime'),60);
                                	echo $hour.' Hours '.$minute.' Minutes'; 
                                } 
                                else 
                                { echo '24 Hours'; }
                                ?>
                                </span> )</button>
                                </li>

                                <li class="clearDivider fullbtn">
                                	<button class="fullButton language_btn">Language ( English )</button>
                                </li>


				<li class="clearDivider fullbtn">
                                	<button class="fullButton delay_btn">Send Delay</button>
                                </li>

								
				<li class="clearDivider fullbtn">
                                <button class="bubble_color">Bubble Color ( <span id="bubble_page_value">
                                <?php 
                                if($this->getValue('color')!="") 
                                { 
                                	echo $this->getValue('color');
                                } 
                                else 
                                { echo 'Default'; }
                                ?>
                                </span> )</button>
                                </li>
                                
                                <li data-role="list-divider" class="clearDivider p6"><?php echo $this->t('Membership Status'); ?></li>
                                <li data-icon="gear">
                               		<a href="#" class="safetext-membership-options-button">
                                        <h2><?php if ($this->getValue('user')->subscription_level < 1) echo $this->t('Not Active'); else echo $this->t('Active'); ?></h2>
                                        <p style="white-space: normal;"><strong><?php if ($this->getValue('user')->subscription_level < 1) echo $this->t('Subscribe today to activate your account and enable message sending'); else if ($this->getValue('user')->subscription_recurs === '1') echo $this->t('Auto-renews on') . ' ' . date('M jS, Y', strtotime($this->getValue('user')->subscription_expires)); else echo $this->t('Expires on') . ' ' . date('M jS, Y', strtotime($this->getValue('user')->subscription_expires)); ?></strong></p>
                                    </a>
                                </li>
                                
                                <?php if (sizeof($this->getValue('devices')) > 0): ?>
                              		<li data-role="list-divider"><?php echo $this->t('Registered Devices'); ?></li>
							  		<?php foreach ($this->getValue('devices') as $this_device) : ?>
	                               <li id="safetext-devicelisting-<?php echo $this_device->id; ?>" data-icon="delete" data-safetext-device-id="<?php echo $this_device->id; ?>">
	                               		<a href="#" class="safetext-delete-button">
	                                        <h2><?php echo $this_device->description; ?></h2>
	                                        <p><strong><?php echo $this->t('Signature'); ?>:</strong> <?php echo $this_device->signature; ?></p>
											<?php if ($this_device->is_initialized != '1') echo '<p> &middot; <em>' . $this->t('Not yet synchronized') . '</em></p>'; ?>
										</a>
	                                </li>
	                            <?php endforeach; ?>
                                
                                <?php endif; ?>
                            </ul>
                        </form>
                   </div>
            </div>

	    	
	    </div><!-- /content -->
	
	<!-- unregister popup -->
		<div class="safetext-confirm-delete-popup" data-role="popup" data-overlay-theme="b" data-theme="b" data-dismissible="false" style="max-width:400px;">
	    	<a href="#" data-rel="back" class="ui-btn ui-corner-all ui-shadow ui-btn-a ui-icon-delete ui-btn-icon-notext ui-btn-right">Close</a>
	        <div data-role="header" data-theme="a">
	            <h1><?php echo $this->t('Unregister Device'); ?>?</h1>
	        </div>
	        <div role="main" class="ui-content">
	            <h3 class="ui-title"><?php echo $this->t('Please confirm'); ?></h3>
	            <p><?php echo $this->t('This device will be unregistered and any on-server sync data will be removed'); ?>.</p>
	            <fieldset class="ui-grid-a">
		            <div class="ui-block-a"><a href="#" class="ui-btn ui-corner-all ui-shadow ui-btn-b" data-rel="back">Cancel</a></div>
		            <div class="ui-block-b"><a href="#" class="ui-btn ui-corner-all ui-shadow ui-btn-b safetext-confirm-unregister-button" 
		                data-safetext-deletedevice-id=""
						data-rel="back" data-transition="flow"><?php echo $this->t('Unregister'); ?></a></div>
	            </fieldset>
	        </div>
	    </div>
    <!-- /delete message popup -->
    
    <!-- subscription options popup -->
    	<div data-role="popup" class="safetext-subscription-options-menu" data-theme="b">
			<a href="#" data-rel="back" class="ui-btn ui-corner-all ui-shadow ui-btn-a ui-icon-delete ui-btn-icon-notext ui-btn-right">Close</a>
            <ul data-role="listview" data-inset="true" style="min-width:210px;">
                <li data-role="list-divider"><?php echo $this->t('Update Subscription'); ?></li>
                <?php if ($this->getValue('user')->subscription_level < 1) : ?>
                	<li data-icon="carat-r"><a href="/settings/subscribe" class="safetext-subscribe-button" data-safetext-sendmessage-id=""><?php echo $this->t('Subscribe'); ?></a></li>
                <?php elseif ($this->getValue('user')->subscription_recurs === '1') : ?>
                	<li data-icon="carat-r"><a href="#" class="safetext-disable-autorenew-button" data-safetext-sendmessage-id=""><?php echo $this->t('Disable Auto-Renew'); ?></a></li>
                <?php else: ?>
                	<li data-icon="carat-r"><a href="/settings/subscribe" class="safetext-subscribe-button" data-safetext-sendmessage-id=""><?php echo $this->t('Extend'); ?></a></li>
                <?php endif; ?>
                <li data-icon="carat-r"><a href="/settings/payments" class="safetext-paymenthistory-button" data-safetext-deletemessage-id=""><?php echo $this->t('Payment History'); ?></a></li>
                <li data-icon="carat-r"><a href="/settings/card" class="safetext-updatecard-button" data-safetext-deletemessage-id=""><?php echo $this->t('Change Payment Card'); ?></a></li>
            </ul>
        </div>
	<!-- /subscription options popup -->
	<style>
	.w50{
	margin: 5px !important;
	float: left;
	width: 44.8%;
	clear:none;
	height: 70px;
	}
	
	.safetext-settings-form .clearDivider{
	display: block;
clear: both;
float: none;
width: auto;
	}
	
	.ui-field-contain div.ui-slider-switch, .ui-field-contain.ui-hide-label div.ui-slider-switch, html .ui-popup .ui-field-contain div.ui-slider-switch {
display: inline-block;
width: 5.8em !important;
}
	
	.ui-slider-track .ui-btn.ui-slider-handle{

	border-radius: 55px !important;
}
	div.ui-slider-switch{
	height: 34px;

	margin-top: 5px !important;
	}
	.p6{padding:6px !important}
	</style>
	    
	<?php echo $this->render('webclient/_footer.phtml'); ?>
		
</div> <!--/page-->

<!-- settings popup menu -->
<div data-role="popup" data-theme="a" class="safetext-message-settings-popup2 ui-corner-all">
	
    <form class="safetext-message-settings-form">
        <div style="padding:10px 20px;">
        <a href="#" data-rel="back" class="ui-btn ui-corner-all ui-shadow ui-btn-a ui-icon-delete ui-btn-icon-notext ui-btn-right">Close</a>
		<div align="center"><h3><?php echo $this->t('Message Settings'); ?></h3></div>
		
		<div class="dtpicker-components"><div class="dtpicker-compOutline dtpicker-comp2"><div class="dtpicker-comp hour"><a class="dtpicker-compButton increment_hour dtpicker-compButtonEnable">+</a><input type="text" id="setting_hour" class="dtpicker-compValue" value="24" readonly><a class="dtpicker-compButton decrement_hour dtpicker-compButtonEnable">-</a></div></div><div class="dtpicker-compOutline dtpicker-comp2"><div class="dtpicker-comp minutes"><a class="dtpicker-compButton increment_minute dtpicker-compButtonEnable">+</a><input type="text" id="setting_minute" class="dtpicker-compValue" value="0"><a class="dtpicker-compButton decrement_minute dtpicker-compButtonEnable">-</a></div></div></div>
        
        <a href="#" class="safetext-message-settings-apply-button2 ui-btn ui-corner-all ui-shadow"><?php echo $this->t('Apply'); ?></a>    
            
        </div>
    </form>
</div>
<!-- /settings -->

<!---Bubble Color --->

<div data-role="popup" data-theme="a" class="safetext-bubble ui-corner-all">
	
    <form class="safetext-bubble-form">
    <input type="hidden" name="user_id" id="user_id" value="<?php echo $this->getValue('user')->id; ?>">
        <div style="padding:10px 20px;">
        
        <ul>
        <li class="bubble_value">Default</li>
        <li class="bubble_value">Blue</li>
        <li class="bubble_value">Green</li>
        <li class="bubble_value">Orange</li>
        <li class="bubble_value">Pink</li>
        <li class="bubble_value">Yellow</li>
        </ul> 
            
        </div>
    </form>
</div>


<!---Language Popup--->

<div data-role="popup" data-theme="a" class="safetext-language ui-corner-all">
	
    <form class="safetext-language-form">
        <div style="padding:10px 20px;">
        
        <ul>
        <li class="language_value">English</li>
        </ul> 
            
        </div>
    </form>
</div>

<!---Delay Popup--->

<div data-role="popup" data-theme="a" class="safetext-delay ui-corner-all">
	
    <form class="safetext-delay-form">
        <div style="padding:10px 20px;">
        
        <ul>
        <li class="delay_value">5</li>
	<li class="delay_value">10</li>
	<li class="delay_value">15</li>
	<li class="delay_value">20</li>
        </ul> 
            
        </div>
    </form>
</div>