<!-- composer footer -->
<div data-role="footer" data-position="fixed" data-theme="b">
    <div class="ui-bar ui-bar-b">
		<form>
			<div class="safetext-footer-composer-input">
				<label for="composer" class="ui-hidden-accessible">Compose Input:</label>
				<textarea name="composer" data-mini="true" placeholder="New Message" data-clear-btn="true" data-theme="a"></textarea>
			</div>
			<div class="safetext-footer-composer-button">
				<button type="button" class="ui-btn ui-btn-a ui-corner-all ui-shadow"><?php echo $this->t('Send'); ?></button>
			</div>
		</form>
	</div>
</div>
<!-- /footer-->