<!-- composer footer -->
<div data-role="footer" data-position="fixed" data-theme="b">
    <div class="ui-bar ui-bar-b">
		<form>
			<div class="safetext-footer-composer-input">
				<label for="composer" class="ui-hidden-accessible">Compose Input:</label>
				<textarea class="safetext-new-message"
					<?php if ($this->getValue('user')->subscription_level < 1) : ?>disabled="disabled"<?php endif; ?>
					data-safetext-contact="<?php echo $this->getValue('contact'); ?>"
					data-safetext-isdraft="0"
					data-safetext-isimportant="0"
					data-safetext-lifetime="24"
					name="composer" data-mini="true" placeholder="<?php if ($this->getValue('user')->subscription_level < 1) echo $this->t('Subscribe to enable messaging'); else echo $this->t('New Message'); ?>" data-clear-btn="true" data-theme="a"></textarea>
			</div>
			<div class="safetext-footer-composer-button">
				<div class="ui-grid-a center">
				    <div data-role="controlgroup" data-type="horizontal" data-mini="true" class="safetext-mobile-only">
					    <a href="#" class="safetext-new-message-button ui-btn ui-corner-all ui-icon-carat-r ui-btn-icon-notext"><?php echo $this->t('Send'); ?></a>
					    <a href="#" class="safetext-message-settings-button ui-btn ui-corner-all ui-icon-gear ui-btn-icon-notext"><?php echo $this->t('Settings'); ?></a>
					</div>
					<div data-role="controlgroup" data-type="horizontal" class="safetext-mobile-hidden">
					    <a href="#" class="safetext-new-message-button ui-btn ui-corner-all ui-icon-carat-r ui-btn-icon-right"><?php echo $this->t('Send'); ?></a>
					    <a href="#" class="safetext-message-attach-button ui-btn ui-corner-all ui-icon-camera ui-btn-icon-right">&nbsp;</a>
					    <a href="#" class="safetext-message-settings-button ui-btn ui-corner-all ui-icon-gear ui-btn-icon-right">&nbsp;</a>
					</div>
				</div><!-- /grid-a -->
			</div>
		</form>
	</div>
</div>
<!-- /footer-->

<!-- settings popup menu -->
<div data-role="popup" data-theme="a" class="safetext-message-settings-popup ui-corner-all">
	<a href="#" data-rel="back" class="ui-btn ui-corner-all ui-shadow ui-btn-a ui-icon-delete ui-btn-icon-notext ui-btn-right">Close</a>
    <form class="safetext-message-settings-form">
        <div style="padding:10px 20px;">
            <h3><?php echo $this->t('Message Settings'); ?></h3>
            <!--
            <fieldset data-role="controlgroup" data-theme="a">
			    <input type="checkbox" name="isdraft" id="isdraft">
			    <label for="isdraft"><?php echo $this->t('Draft'); ?></label>
			    <input type="checkbox" name="isimportant" id="isimportant">
			    <label for="isimportant"><?php echo $this->t('Important'); ?></label>
            </fieldset>
            -->
            
            <label for="lifetime"><?php echo $this->t('Hours to expire'); ?>:</label>
            <input type="text" name="lifetime" value="24" data-theme="a">
            
            <a href="#" class="safetext-message-settings-apply-button ui-btn ui-corner-all ui-shadow"><?php echo $this->t('Apply'); ?></a>
        </div>
    </form>
</div>
<!-- /settings -->

<!-- attach image popup message -->
<div data-role="popup" data-theme="a" class="safetext-message-attach-popup ui-corner-all">
	<a href="#" data-rel="back" class="ui-btn ui-corner-all ui-shadow ui-btn-a ui-icon-delete ui-btn-icon-notext ui-btn-right">Close</a>
	<?php if ($this->getValue('user')->subscription_level < 1) : ?>
		<div style="padding:10px 20px;">
			<?php echo $this->t('Subscribe today to enable image uploads!'); ?>
		</div>
	<?php else: ?>
		<form action="https://safe-text.us/api/images/" method="post" enctype="multipart/form-data" class="safetext-message-attach-form">
	        <div style="padding:10px 20px;">
	            <h3><?php echo $this->t('Send Image'); ?></h3>
	            <fieldset data-role="controlgroup" data-theme="a">
				    <input type="file" name="image">
	            </fieldset>
	            
	            <a href="#" class="safetext-message-attach-send-button ui-btn ui-corner-all ui-shadow"><?php echo $this->t('Send'); ?></a>
	        </div>
	    </form>
		<div id="progressbox" ><div id="progressbar"></div ><div id="statustxt">0%</div></div>
		<div id="output"></div>
	<?php endif; ?>
</div>
<!-- /attach image -->
