<!-- header - with web client nav -->
<!-- fixed header -->
<script src="/assets/js/classie.js"></script>
<script>
    function init() {
        window.addEventListener('scroll', function(e){
            var distanceY = window.pageYOffset || document.documentElement.scrollTop,
                shrinkOn = 300,
                header = document.querySelector("header");
            if (distanceY > shrinkOn) {
                classie.add(header,"smaller");
            } else {
                if (classie.has(header,"smaller")) {
                    classie.remove(header,"smaller");
                }
            }
        });
    }
    window.onload = init();
</script>
<!-- end -->
<header data-role="header" class="safetext-header" data-position="fixed">
	<div class="toparea">
    <h1><?php echo $this->title; ?></h1>
    <div class="userDiv">
        	<p>Welcome</p>
            <a href="/webclient/messages" data-transition="fade"><?php echo $this->getValue('user')->username; ?></a>
        </div>
	<div class="safetext-nav clearfix"> 
        <ul class="clearfix">
		   <li><a href="/settings" data-transition="fade"><?php echo $this->t('Settings'); ?></a></li>  
		   <li><a href="<?php if ($this->getValue('user')->subscription_level > 0) echo '/settings/payments'; else echo '/settings/subscribe'; ?>" data-transition="fade"><?php if ($this->getValue('user')->subscription_level > 0) echo $this->t('Payments'); else echo $this->t('Subscribe'); ?></a></li>
		   <li><a href="/auth/logout" data-ajax="false"><?php echo $this->t('Logout'); ?></a></li>
        </ul>
    </div>
	</div>
    <a data-role="button" onclick="$('.leftpanel:visible').panel('open');" href="#" data-icon="bars"
		data-iconpos="notext" class="ui-btn-left">Menu</a>
</header>
<!-- /header -->
<style>
.safetext-header { position:fixed;top:0;left:0;z-index: 99999; }
</style>
