<!-- header - with web client nav -->
<div data-role="header" class="safetext-header" data-position="fixed">
	<h1><?php echo $this->title; ?></h1>
	
	<div class="safetext-nav clearfix">
        <ul class="clearfix">
           <li><a href="/webclient/messages" data-transition="fade"><?php echo $this->getValue('user')->username; ?></a></li>  
		   <li><a href="/settings" data-transition="fade"><?php echo $this->t('Settings'); ?></a></li>  
		   <li><a href="<?php if ($this->getValue('user')->subscription_level > 0) echo '/settings/payments'; else echo '/settings/subscribe'; ?>" data-transition="fade"><?php if ($this->getValue('user')->subscription_level > 0) echo $this->t('Payments'); else echo $this->t('Subscribe'); ?></a></li>
		   <li><a href="/auth/logout" data-ajax="false"><?php echo $this->t('Logout'); ?></a></li>
        </ul>
    </div>
	
    <a data-role="button" onclick="$('.leftpanel:visible').panel('open');" href="#" data-icon="bars"
		data-iconpos="notext" class="ui-btn-left">Menu</a>
	<a data-role="button" href="/webclient/contactadd" data-icon="plus"
		data-iconpos="notext" class="ui-btn-right">Add</a>
</div>
<!-- /header -->
