<!-- header - with web client conversation view nav -->
<div data-role="header" class="safetext-header" data-position="fixed">
	<h1><?php echo $this->title; ?></h1>
	
	<div class="safetext-nav clearfix">
        <ul class="clearfix">
           <li><a href="/webclient/messages" data-transition="fade"><?php echo $this->getValue('user')->username; ?></a></li>  
		   <li><a href="/settings" data-transition="fade"><?php echo $this->t('Settings'); ?></a></li>  
		   <li><a href="#" data-transition="fade"><?php echo $this->t('Payment'); ?></a></li>
		   <li><a href="/auth/logout" data-ajax="false"><?php echo $this->t('Logout'); ?></a></li>
        </ul>
    </div>
	
    <a data-role="button" href="/webclient/contacts" data-icon="carat-l"
		data-iconpos="notext" class="ui-btn-left">Back</a>
</div>
<!-- /header -->