<!-- header - with web client nav -->
<div data-role="header" class="safetext-header" data-position="fixed">
<div class="toparea">
	<h1><?php echo $this->title; ?></h1>
    <div class="userDiv">
        	<p>Welcome</p>
            <a href="/webclient/messages" data-transition="fade"><?php echo $this->getValue('user')->username; ?></a>
     </div>
	<div class="safetext-nav clearfix">
        <ul class="clearfix">
		   <li><a href="/settings" data-transition="fade"><?php echo $this->t('Settings'); ?></a></li>  
		   <li><a href="<?php if ($this->getValue('user')->subscription_level > 0) echo '/settings/payments'; else echo '/settings/subscribe'; ?>" data-transition="fade"><?php if ($this->getValue('user')->subscription_level > 0) echo $this->t('Payments'); else echo $this->t('Subscribe'); ?></a></li>
		   <li><a href="/auth/logout" data-ajax="false"><?php echo $this->t('Logout'); ?></a></li>
        </ul>
    </div>
	</div>
    <a data-role="button" href="#" data-rel="back" data-icon="carat-l"
		class="ui-btn-left"><?php echo $this->t('Cancel'); ?></a>
	<a data-role="button" href="#" data-icon="check"
		class="safetext-save-contact-button ui-btn-right"><?php echo $this->t('Done'); ?></a>
</div>
<!-- /header -->