<!-- header - with web client nav -->
<div data-role="header" class="safetext-header" data-position="fixed">
	<h1><?php echo $this->title; ?></h1>
	
	<div class="safetext-nav clearfix">
        <ul class="clearfix">
           <li><a href="/webclient/messages" data-transition="fade"><?php echo $this->getValue('user')->username; ?></a></li>  
		   <li><a href="/settings" data-transition="fade"><?php echo $this->t('Settings'); ?></a></li>  
		   <li><a href="#" data-transition="fade"><?php echo $this->t('Payment'); ?></a></li>
		   <li><a href="/auth/logout" data-ajax="false"><?php echo $this->t('Logout'); ?></a></li>
        </ul>
    </div>
	
    <a data-role="button" href="#" data-rel="back" data-icon="carat-l"
		class="ui-btn-left"><?php echo $this->t('Cancel'); ?></a>
	<a data-role="button" href="#" data-icon="check"
		class="safetext-save-contact-button ui-btn-right"><?php echo $this->t('Done'); ?></a>
</div>
<!-- /header -->