<div data-role="page" class="safetext-page safetext-contacts" data-title="<?php if ($this->getValue('filter') === 'blocked') echo $this->t('Blocked'); ?> <?php echo $this->t('Contacts'); ?>">
		
		<?php echo $this->render('webclient/_leftpanel.phtml'); ?>
		<?php echo $this->render('webclient/_header_contacts.phtml'); ?>
	
	    <div data-role="content" class="safetext-content" data-theme="a">
	    	
		    <div class="safetext-client-grid">
		    	<!-- Left-hand Folder Column -->
			    <div class="safetext-block-a">
			    	<div class="ui-body ui-body-d">
					    <div><a href="/webclient/contactadd" class="safetext-add-contact-button ui-btn ui-icon-plus ui-btn-icon-left ui-corner-all ui-shadow"><?php echo $this->t('Add Contact'); ?></a></div>
					    <?php echo $this->render('webclient/_foldermenu.phtml'); ?>
					</div>
			    </div>
			    
			    <!-- Main Content Column -->
			    <div class="safetext-block-b">
			    	<div class="ui-body ui-body-d">
				    	<div class="ui-grid-b safetext-mobile-hidden">
						    <div class="ui-block-a"><a href="/webclient/messages" class="ui-btn ui-corner-all ui-btn-icon-left ui-icon-mail">Messages</a></div>
						    <div class="ui-block-b"><a href="/webclient/contacts" class="ui-shadow ui-btn ui-corner-all ui-btn-icon-left ui-icon-user ui-btn-active">Contacts</a></div>
						    <div class="ui-block-c"><a href="/settings" class="ui-btn ui-corner-all ui-btn-icon-left ui-icon-gear">Settings</a></div>
						</div>
						
						<div>
						    <ul data-role="listview" data-autodividers="true" data-split-icon="edit" data-filter="true" data-inset="true">
						    	<?php foreach ($this->getValue('contacts') as $this_contact) : ?>
						    		<?php if ($this->getValue('filter') === '' || $this_contact->is_blocked === '1') : ?>
						    		<li><a href="/webclient/conversation/contact/<?php echo $this_contact->contact_user_id; ?>">
						    			<h2><?php echo $this_contact->label(); ?></h2>
						    			<?php if ($this_contact->phone !== '') : ?>
						    				<p style="float:left; margin-right:5px;"><strong><?php echo $this->t('Tel'); ?>:</strong> <?php echo $this_contact->phone; ?></p>
						    			<?php endif; ?>
						    			<?php if ($this_contact->email !== '') : ?>
						    				<p style="float:left;"><strong><?php echo $this->t('Email'); ?>:</strong> <?php echo $this_contact->email; ?></p>
						    			<?php endif; ?></a>
										<a href="/webclient/contact/id/<?php echo $this_contact->contact_user_id; ?>"></a>
						    		</li>
						    		<?php endif; ?>
						    	<?php endforeach; ?>
							</ul>
						</div>
						    
			    	</div>
			    </div>

			</div>
	    
	    </div><!-- /content -->
	
	<?php echo $this->render('webclient/_footer.phtml'); ?>
		
</div> <!--/page-->