<div data-role="page" class="safetext-page safetext-contact" data-title="<?php echo $this->t('Edit'); ?> <?php echo $this->getValue('contactName'); ?>">
		
		<div data-role="panel" class="leftpanel" data-position="left" data-display="reveal" data-theme="b"></div>
		<?php echo $this->render('webclient/_header_contact.phtml'); ?>
	
	    <div data-role="content" class="safetext-content" data-theme="a">
	    	
		    <div class="safetext-client-grid">
		    	<!-- Left-hand Folder Column -->
			    <div class="safetext-block-a">
			    	<div class="ui-body ui-body-d">
					    
					    <?php echo $this->render('webclient/_foldermenu.phtml'); ?>
					</div>
			    </div>
			    
			    <!-- Main Content Column -->
			    <div class="safetext-block-b">
			    	<div class="ui-body ui-body-d">
				    	<div class="ui-grid-b safetext-mobile-hidden">
						    <div class="ui-block-a"><a href="/webclient/messages" class="ui-btn ui-corner-all ui-btn-icon-left ui-icon-mail">Messages</a></div>
						    <div class="ui-block-b"><a href="/webclient/contacts" class="ui-shadow ui-btn ui-corner-all ui-btn-icon-left ui-icon-user ui-btn-active">Contacts</a></div>
						    <div class="ui-block-c"><a href="/webclient/settings" class="ui-btn ui-corner-all ui-btn-icon-left ui-icon-gear">Settings</a></div>
						</div>
						
						<div>
						    <?php if ($this->getValue('contactObject') instanceof SafetextContact) : ?>
						    	<!-- edit contact form -->
						    	<form class="safetext-edit-contact-form">
								    <ul data-role="listview" data-inset="true">
								    	<li data-role="list-divider"><?php echo $this->t('Edit'); ?> <?php echo $this->getValue('contactName'); ?></li>
								        <li class="ui-field-contain">
								            <label for="name"><?php echo $this->t('Name'); ?>:</label>
								            <input type="text" name="name" value="<?php echo $this->getValue('contactObject')->name; ?>" data-clear-btn="true">
								        </li>
								        <li class="ui-field-contain">
								            <label for="phone"><?php echo $this->t('Phone'); ?>:</label>
								            <input type="text" name="phone" value="<?php echo $this->getValue('contactObject')->phone; ?>" data-clear-btn="true">
								        </li>
								        <li class="ui-field-contain">
								            <label for="email"><?php echo $this->t('Email'); ?>:</label>
								            <input type="text" name="email" value="<?php echo $this->getValue('contactObject')->email; ?>" data-clear-btn="true">
								        </li>
								        <li class="ui-field-contain">
								            <label for="whitelist"><?php echo $this->t('Whitelist'); ?>:</label>
								            <select name="whitelist" data-role="slider">
								                <option value="0"><?php echo $this->t('No'); ?></option>
								                <option value="1"<?php if ($this->getValue('contactObject')->is_whitelist === '1') echo ' selected'; ?>><?php echo $this->t('Yes'); ?></option>
								            </select>
								        </li>
								        <li class="ui-field-contain">
								            <label for="blocked"><?php echo $this->t('Blocked'); ?>:</label>
								            <select name="blocked" data-role="slider">
								                <option value="0"><?php echo $this->t('No'); ?></option>
								                <option value="1"<?php if ($this->getValue('contactObject')->is_blocked === '1') echo ' selected'; ?>><?php echo $this->t('Yes'); ?></option>
								            </select>
								        </li>
								        <li class="ui-field-contain">
								            <fieldset class="ui-grid-a safetext-mobile-hidden">
								                    <div class="ui-block-a"><a href="#" data-rel="back" class="ui-btn ui-icon-carat-l ui-btn-icon-left ui-corner-all ui-shadow"><?php echo $this->t('Cancel'); ?></a></div>
								                    <div class="ui-block-b"><a href="#" class="safetext-save-contact-button ui-btn ui-icon-check ui-btn-icon-left ui-corner-all ui-shadow"><?php echo $this->t('Save'); ?></a></div>
								            </fieldset>
								        </li>
								        <li data-role="list-divider" data-theme="c"><?php echo $this->t('Remove This Contact'); ?></li>
								        <li class="ui-field-contain" data-theme="c">
								        	<fieldset class="center">
								            	<a href="#safetext-removecontact-<?php echo $this->getValue('contact'); ?>" class="ui-btn ui-icon-delete ui-btn-icon-left ui-corner-all ui-shadow" data-rel="popup" data-transition="pop"><?php echo $this->t('Remove Contact'); ?></a>
								            </fieldset>
								        </li>
								    </ul>
								    <input type="hidden" name="contact" value="<?php echo $this->getValue('contact'); ?>" />
								</form>
								<!-- /edit contact form -->
						    <?php else : ?>
						    	<ul data-role="listview" data-split-icon="delete" data-split-theme="a" data-inset="true">
		                            <div data-role="content" class="ui-body-c">
		                                <div class="safetext-content">
		                                    <p><?php echo $this->t("This isn't a valid contact"); ?>.</p>
		                                </div>
		                            </div>
						    
						    <?php endif; ?>
						</div>
						    
			    	</div>
			    </div>

			</div>
	    
	    </div><!-- /content -->
	
	<!-- remove contact popup -->
	<div data-role="popup" id="safetext-removecontact-<?php echo $this->getValue('contact'); ?>" data-overlay-theme="b" data-theme="b" data-dismissible="false" style="max-width:400px;">
    	<a href="#" data-rel="back" class="ui-btn ui-corner-all ui-shadow ui-btn-a ui-icon-delete ui-btn-icon-notext ui-btn-right">Close</a>
        <div data-role="header" data-theme="a">
            <h1><?php echo $this->t('Remove Contact'); ?>?</h1>
        </div>
        <div role="main" class="ui-content">
            <h3 class="ui-title"><?php echo $this->t('Confirm remove contact'); ?></h3>
            <p><?php echo $this->t('This contact will no longer appear in your contacts list'); ?>.</p>
            <fieldset class="ui-grid-a">
	            <div class="ui-block-a"><a href="#" class="ui-btn ui-corner-all ui-shadow ui-btn-b" data-rel="back">Cancel</a></div>
	            <div class="ui-block-b"><a href="#" class="ui-btn ui-corner-all ui-shadow ui-btn-b safetext-remove-contact-button" 
	                data-safetext-contact="<?php echo $this->getValue('contact'); ?>"
					data-rel="back" data-transition="flow"><?php echo $this->t('Remove'); ?></a></div>
            </fieldset>
        </div>
    </div>
    <!-- /remove contact popup -->
	
	<?php echo $this->render('webclient/_footer.phtml'); ?>
		
</div> <!--/page-->