<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js">
</script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jstimezonedetect/1.0.4/jstz.min.js">
</script>
<style>
.ser .ui-filterable{ display:none; }

.group_checkbox { float:right !important; left:0 !important; margin-right:36px !important;margin-top:-51px !important;position:relative !important; width:30px !important;   }
</style>
<div data-role="page" class="safetext-page safetext-contacts" data-title="<?php if ($this->getValue('filter') === 'blocked') echo $this->t('Blocked'); ?> <?php echo $this->t('Contacts'); ?>">
		
		<?php echo $this->render('webclient/_leftpanel.phtml'); ?>
		<?php echo $this->render('webclient/_header.phtml'); ?>
	
	    <div data-role="content" class="safetext-content" data-theme="a">
	    	
		    <div class="safetext-client-grid">
		    	<!-- Left-hand Folder Column -->
			    <div class="safetext-block-a">
			    	<div class="ui-body ui-body-d">
					    <div><a href="/webclient/contactadd" class="safetext-add-contact-button ui-btn ui-icon-plus ui-btn-icon-left ui-corner-all ui-shadow"><?php echo $this->t('Add Contact'); ?></a></div>
					    <?php echo $this->render('webclient/_foldermenu.phtml'); ?>
					</div>
			    </div>
			    
			    <!-- Main Content Column -->
			    <div class="safetext-block-b">
			    	<div class="ui-body ui-body-d">
				    		<div class="ui-grid-a safetext-mobile-hidden">
						    <div class="ui-block-a" style="width:99%;float:left;clear:none"><a href="" class="ui-btn ui-corner-all ui-btn-icon-left ui-icon-user ui-btn-active">Group</a></div>
					 	</div>
						
						<div class="contactListWrapper ser">
						
						<form id="add_group_form">
						
						    <input type="text" name="group_name" id="group_name" placeholder="Group Name">
							
							<input type="hidden" name="user_id" id="user_id" value="<?php echo $this->getValue('user_id'); ?>">
						    
						    <ul data-role="listview" data-autodividers="true" data-icon="null" data-filter="true" data-inset="true">
						    	<?php foreach ($this->getValue('contacts') as $this_contact) : ?>
						    		<?php if (($this->getValue('filter') === 'blocked' && $this_contact->is_blocked==='1') || ($this->getValue('filter') === '' && $this_contact->is_blocked === '0')) : ?>
						    		<li><a href="" style="cursor:default">
						    			<h2><?php echo $this_contact->label(); ?></h2>
										<p style="margin-right:5px;">
						    			<?php if ($this_contact->notes !== '') { ?>
						    				<strong><?php echo $this->t('Note'); ?>:</strong> <?php echo $this_contact->notes; ?>
						    			<?php } else { echo "&nbsp"; }?> 
										</p>
						    			<?php /*?><?php if ($this_contact->phone !== '') : ?>
						    				<p style="margin-right:5px;"><strong><?php echo $this->t('Tel'); ?>:</strong> <?php echo $this_contact->phone; ?></p>
						    			<?php endif; ?>
						    			<?php if ($this_contact->email !== '') : ?>
						    				<p><strong><?php echo $this->t('Email'); ?>:</strong> <?php echo $this_contact->email; ?></p>
						    			<?php endif; ?><?php */?></a>
						    				<input class="group_checkbox" type="checkbox" value="<?php echo $this_contact->contact_user_id; ?>" name="group_contact" id="group_contact" style="cursor:pointer">
										<!--<a href="/webclient/contact/id/<?php echo $this_contact->contact_user_id; ?>"></a>-->
						    		</li>
						    		<?php endif; ?>
						    	<?php endforeach; ?>
						   </ul>
						   <input type="submit" value="Done" id="safetext-group-add" class="safetext-group-add">
						  
						  </form>
						   
						</div>
						    
			    	</div>
			    </div>

			</div>
	    
	    </div><!-- /content -->
	
	<?php echo $this->render('webclient/_footer.phtml'); ?>
		
</div> <!--/page-->