<div data-role="page" class="safetext-page safetext-home" data-title="<?php echo $this->t('Dashboard'); ?>">
		<div class="heaver-img"></div>	
		<?php echo $this->render('webclient/_leftpanel.phtml'); ?>
		<?php echo $this->render('webclient/_header.phtml'); ?>
	
	    <div data-role="content" class="safetext-content" data-theme="a">
	    	<h2><?php echo $this->t('Coming Soon: Web Client Dashboard'); ?></h2>
	    	<p>
	    		The web client is currently in development.
	    	</p>
	    </div><!-- /content -->
	    
	    
	    
	    
	    
	    
	
	<?php echo $this->render('webclient/_footer.phtml'); ?>
		
</div> <!--/page-->