<!-- footer -->
<div data-role="footer" data-theme="b">
	<div data-role="navbar" class="safetext-footer-nav">
        <ul>
            <li><a href="#"><?php echo $this->t('About Us'); ?></a></li>
            <li><a href="#"><?php echo $this->t('FAQs'); ?></a></li>
            <li><a href="#"><?php echo $this->t('Privacy'); ?></a></li>
            <li><a href="#"><?php echo $this->t('Contact Us'); ?></a></li>
        </ul>
    </div><!-- /footer navbar -->
    
    <!-- disclaimer -->
	<div class="ui-body-bg safetext-disclaimer">
		Disclaimer: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas adipiscing ultricies molestie. Aliquam erat volutpat. Nullam id urna ante.
		Mauris odio metus, ultricies consectetur magna quis, volutpat pulvinar ligula.
	</div>
	<!-- /disclaimer -->
    <h3>&copy; <?php echo date('Y'); ?> Safe-Text. All rights reserved.</h3>
</div>
<!-- /footer-->