<!-- left panel - front site mobile nav  -->
<div data-role="panel" class="leftpanel" data-position="left" data-display="reveal" data-theme="b">
	<div>
		<p><?php if ($this->getValue('user') instanceof SafetextUser) echo $this->getValue('user')->fullName(); ?></p>
		
		<ul data-role="listview">
			<?php if (!$this->getValue('user') instanceof SafetextUser) : ?>
				<li><a href="/auth/login" data-transition="fade"><?php echo $this->t('Login'); ?></a></li>
				<li><a href="/auth/register" data-transition="fade"><?php echo $this->t('New User Registration'); ?></a></li>
				<li><a href="/auth/password" data-transition="fade"><?php echo $this->t('Recover Password'); ?></a></li>
			<?php else : ?>
				<li><a href="/dashboard/home" data-ajax="false"><?php echo $this->t('My Dashboard'); ?></a></li>
				<li><a href="/auth/logout" data-ajax="false"><?php echo $this->t('Log Out'); ?></a></li>
			<?php endif; ?>
			<li data-role="list-divider"></li>
			<li><a href="/story" data-transition="fade"><?php echo $this->t('Our Story'); ?></a></li>  
			<li><a href="/product" data-transition="fade"><?php echo $this->t('Our Product'); ?></a></li>
			<li><a href="/rules" data-transition="fade"><?php echo $this->t('Our Rules'); ?></a></li>
			<li><a href="/answers" data-transition="fade"><?php echo $this->t('Our Answers'); ?></a></li>
			<li><a href="/about" data-transition="fade"><?php echo $this->t('About Us'); ?></a></li>
			<li><a href="/faq" data-transition="fade"><?php echo $this->t('FAQs'); ?></a></li>
			<li><a href="/privacy" data-transition="fade"><?php echo $this->t('Privacy'); ?></a></li>
			<li><a href="/contact" data-transition="fade"><?php echo $this->t('Contact Us'); ?></a></li>
		</ul>
	</div>
</div><!-- /left panel -->