<div data-role="page" class="safetext-page safetext-about">
		
		<?php echo $this->render('front/_leftpanel.phtml'); ?>
		<?php echo $this->render('front/_header.phtml'); ?>
	
	    <div data-role="content" class="safetext-content" data-theme="a">
	    	<h2><?php echo $this->t('About Safe-Text'); ?></h2>
	    	<p>
	    		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum at lectus sit amet sollicitudin. Nullam sit amet elit ac leo sollicitudin consequat. Mauris odio metus, ultricies consectetur magna quis, volutpat pulvinar ligula. Aenean a molestie quam, in varius mi. Praesent et est risus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent lobortis ante lacinia laoreet elementum. Suspendisse fermentum risus justo, vitae lacinia urna interdum nec. Sed congue erat et euismod condimentum. Donec vehicula lacus lectus, eu aliquet quam elementum at. Integer magna nulla, rutrum in vehicula eget, mollis sit amet leo. Mauris viverra euismod consectetur. Nam posuere dapibus placerat.
	    	</p>
	    	<p>
	    		Donec et justo dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec aliquet venenatis orci sit amet euismod. Nunc vestibulum at diam eget euismod. In hac habitasse platea dictumst. Aenean lobortis sapien vel semper dignissim. Aenean mauris sapien, fringilla ut tristique hendrerit, pulvinar nec ligula. Proin ante velit, venenatis vitae iaculis non, euismod nec turpis. Vestibulum faucibus turpis sit amet aliquam elementum.
	    	</p>
	    	
	    	<h3>Subheadline Here</h3>
	    	<p>
	    		Nullam ut feugiat ipsum. Maecenas sed nisl vel magna ullamcorper dictum. Cras auctor viverra aliquam. Nunc mattis leo eros, non varius risus facilisis ornare. Nulla nec turpis hendrerit, mattis eros mollis, volutpat nisl. Suspendisse convallis faucibus dignissim. Integer ut luctus eros. Ut id mauris tortor. Nulla convallis orci orci.
	    	</p>
	    </div><!-- /content -->
	
	<?php echo $this->render('front/_footer.phtml'); ?>
		
</div> <!--/page-->