<!-- header - with web client nav -->
<!-- fixed header -->
<script src="/assets/js/classie.js"></script>

<!-- end -->
<header data-role="header" class="safetext-header" data-position="fixed">

	<div class="menuWrapper">

	<div class="safetext-nav newbgnav clearfix">

	<div class="topbar">
	<a href="#"><img src="https://safe-text.com/wp-content/uploads/2015/02/logoHeader1.png" alt=""></a>
	<ul>
		<li><a href="/admin/users" class="homeicon"><img src="https://safe-text.com/wp-content/uploads/2015/02/home.png" alt=""></a></li>
		<li class="app"><a href="/admin/account" style="padding-top:40px !important;">Change Password</a></li>
		<li class="join"><a href="/admin/logout" style="padding-top:40px !important;">Logout</a></li>
	</ul>
	</div>
	</div>

	</div>

	<?php if($this->getValue('user')->username!="") {?>
	<div class="toparea">
    <h1><?php echo $this->title; ?></h1>
    <div class="userDiv">
        	<p>Welcome</p>
            <a href="/webclient/messages" data-transition="fade"><?php echo $this->getValue('user')->username; ?></a>
        </div>
	<div class="safetext-nav clearfix"> 
        <ul class="clearfix">
		   <li><a href="/settings" data-transition="fade"><?php echo $this->t('Settings'); ?></a></li>  
		   <li><a href="<?php if ($this->getValue('user')->subscription_level > 0) echo '/settings/payments'; else echo '/settings/subscribe'; ?>" data-transition="fade"><?php if ($this->getValue('user')->subscription_level > 0) echo $this->t('Payments'); else echo $this->t('Subscribe'); ?></a></li>
		   <li><a href="/auth/logout" data-ajax="false"><?php echo $this->t('Logout'); ?></a></li>
        </ul>
    </div>
	</div>
	<?php }?>
    <a data-role="button" onclick="$('.leftpanel:visible').panel('open');" href="#" data-icon="bars"
		data-iconpos="notext" class="ui-btn-left">Menu</a>
</header>
<!-- /header -->
<style>
.safetext-header { position:fixed;top:0;left:0;z-index: 99999; }
.menuWrapper{background-image: none;background-color: #C93F3C;border-bottom: 3px solid #fff;}
.topMenuWP{float:right; }
#menu-top-menu li{display: block;float: left; border:0px;}

#menu-top-menu li a {
text-transform: uppercase;
padding: 0 .8em;
font-size: 20px;
padding-top: 34px;
text-shadow: none !important;
}
#menu-top-menu li a:hover {
-webkit-box-shadow: inset 0 4px 0 0 #ffffff;
box-shadow: inset 0 4px 0 0 #ffffff;
background: transparent;
}

.topbar {
  padding: 0;
  margin: 0 auto;
  width: 1110px;
  height: 79px;
  background: #c93f3c url(https://safe-text.com/wp-content/uploads/2015/02/barbg.jpg) center bottom repeat-x;
}
.newbgnav {
  background: url(https://safe-text.com/wp-content/uploads/2015/02/bluebg.jpg) left top no-repeat;
}
.menuWrapper {
  border: none !important;
  background: #c93f3c url(https://safe-text.com/wp-content/uploads/2015/02/barbg.jpg) center bottom repeat-x !important;
}
.safetext-nav {
  width: 100%;
  max-width: inherit !important;
}
.topbar ul li:first-child {
  margin: 0 560px 0 0;
  padding-top: 0;
}
.topbar a {
  float: left;
}
.topbar ul {
  float: left;
  padding: 0;
  margin: 4px 0 0 0;
  width: 88%;
}
.topbar ul li {
  float: left;
  border: none;  
}
.topbar ul li a:hover { text-decoration:none;background:none !important;}
.topbar ul li a {
  float: left;
  padding: 0px 0px 0 0px !important;
  margin: 0;
  border: none;
  text-transform: uppercase;
  text-shadow: none;
  font-size: 14px;
}  
.company {
  background-image: url(https://safe-text.com/wp-content/uploads/2015/02/company.png);
  background-position: center top;
  background-repeat: no-repeat;
  margin-right:70px !important;
}  
.company a { padding-top:40px !important; }
.app {
  background-image: url(https://safe-text.com/wp-content/uploads/2015/02/app.png);
  background-position: center top;
  background-repeat: no-repeat;
  margin-right:70px !important;
}
.difference {
  background-image: url(https://safe-text.com/wp-content/uploads/2015/02/difference.png);
  background-position: center top;
  background-repeat: no-repeat;
  margin-right:70px !important;
}
.join {
  background-image: url(https://safe-text.com/wp-content/uploads/2015/02/login.png);
  background-position: center top;
  background-repeat: no-repeat;
  margin-right:70px !important;
  border:none !important;
}
</style>

<?php
/* set cookie for logout */										
/*end*/
/*if($_COOKIE["timelimit"]=="") {
    echo "Cookie named '" . $_COOKIE["timelimit"] . "' is not set!";
	header("location:/auth/logout");
} else {
    echo "Cookie '" . $_COOKIE["timelimit"] . "' is set!<br>";
    echo "Value is: " . $_COOKIE["timelimit"];
}*/
	
?>
