<?php echo $this->doctype; ?>
<!--[if IEMobile 7 ]>    <html class="no-js iem7"> <![endif]-->
<!--[if (gt IEMobile 7)|!(IEMobile)]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <title><?php echo $this->title; ?></title>
        <meta name="description" content="Application description goes here">
        <meta name="HandheldFriendly" content="True">
        <meta name="MobileOptimized" content="320">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="cleartype" content="on">

        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/images/touch/apple-touch-icon-144x144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/images/touch/apple-touch-icon-114x114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/images/touch/apple-touch-icon-72x72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="/assets/images/touch/apple-touch-icon-57x57-precomposed.png">
        <link rel="shortcut icon" href="/assets/images/touch/apple-touch-icon.png">

        <!-- Tile icon for Win8 (144x144 + tile color) -->
        <meta name="msapplication-TileImage" content="/assets/images/touch/apple-touch-icon-144x144-precomposed.png">
        <meta name="msapplication-TileColor" content="#222222">

        <!-- For iOS web apps. Delete if not needed. https://github.com/h5bp/mobile-boilerplate/issues/94 -->
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">
        <meta name="apple-mobile-web-app-title" content="Safe-Text">
        
        
        <!-- This script prevents links from opening in Mobile Safari. https://gist.github.com/1042026 -->
        <!--
        <script>(function(a,b,c){if(c in b&&b[c]){var d,e=a.location,f=/^(a|html)$/i;a.addEventListener("click",function(a){d=a.target;while(!f.test(d.nodeName))d=d.parentNode;"href"in d&&(d.href.indexOf("http")||~d.href.indexOf(e.host))&&(a.preventDefault(),e.href=d.href)},!1)}})(document,window.navigator,"standalone")</script>
        -->

        <link rel="stylesheet" href="/assets/css/h5bp-mobile-boilerplate-normalize.css" />
        <link rel="stylesheet" href="/assets/css/vendor/jquerymobile/safetext.min.css" />
        <link rel="stylesheet" href="/assets/css/vendor/jquerymobile/jquery.mobile.icons.min.css" />
        <link rel="stylesheet" href="<?php echo MS_PROTOCOL; ?>://code.jquery.com/mobile/1.4.2/jquery.mobile.structure-1.4.2.min.css" />
        <link rel="stylesheet" href="/assets/css/main.css" />
        
        <?php $this->renderStylesheets(); ?>
    </head>
    <body>

        <?php echo $this->content; ?>

        
		<script src="<?php echo MS_PROTOCOL; ?>://code.jquery.com/jquery-1.10.2.min.js"></script>
		<script>
            $(document).bind( 'mobileinit', function(){
              $.mobile.loader.prototype.options.text = "loading";
              $.mobile.loader.prototype.options.textVisible = true;
              $.mobile.loader.prototype.options.theme = "a";
              $.mobile.loader.prototype.options.textonly = false;
              $.mobile.loader.prototype.options.html = "<span class='ui-bar ui-corner-all'><img src='/assets/images/loader.gif' /></span>";
            });
        </script>
		<script src="<?php echo MS_PROTOCOL; ?>://code.jquery.com/mobile/1.4.2/jquery.mobile-1.4.2.min.js"></script>
        <script src="/assets/js/vendor/modernizr-2.6.2.min.js"></script>
        <script src="/assets/js/main.js"></script>
   		<?php $this->renderScriptIncludes(); ?>
   		
   		<script src="/assets/js/helper.js"></script>
        <script>
			$( document ).ready(function() {
				// Add iOS App Startp Images
				MBP.startupImage();
			});
		</script>
		
		<script type="text/javascript" src="/assets/js/vendor/jquery.form.min.js"></script>
    </body>
</html>
