<div data-role="page" class="safetext-page">
	<div class="ui-body-bg safetext-backsplash">
		
		<div data-role="header" class="safetext-header">
			<h1><?php echo $this->title; ?></h1>
		    <a data-role="button" onclick="$('.leftpanel:visible').panel('open');" href="#" data-icon="bars"
	    		data-iconpos="notext" class="ui-btn-left">Menu</a>
		</div><!-- /header -->
	
	    	
	    <div data-role="content" class="safetext-content" data-theme="a">
	    	<div class="safetext-placeholder">
	    		<h2>Coming Soon!</h2>
	    	</div>
	    </div>
		    	
	</div>

	
	<div class="ui-body-bg safetext-disclaimer">
		Disclaimer: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas adipiscing ultricies molestie. Aliquam erat volutpat. Nullam id urna ante.
		Mauris odio metus, ultricies consectetur magna quis, volutpat pulvinar ligula.
	</div>
	
	<div data-role="footer" data-position="fixed" data-theme="b">
		<h3>&copy; <?php echo date('Y'); ?> Safe-Text. All rights reserved</h3>
	</div>
		
</div> <!--/page-->