<div data-role="page" class="safetext-page safetext-password" data-title="<?php echo $this->t('Login Help'); ?>">
		
		<?php echo $this->render('front/_leftpanel.phtml'); ?>
		<?php echo $this->render('front/_header.phtml'); ?>
	
	   <div data-role="content" class="safetext-content" data-theme="a">

	   <h2><?php echo $this->t('Username / Password Help'); ?></h2>
	   <p>
      	<?php echo $this->t("Enter in your email address and we'll send your username and a link to reset your password in an email"); ?>.
	   </p>
	   <p>
      	<?php echo $this->t('Due to the security implications, if you did not set up an email address with your account, we will not be able to provide you with your username or reset your password'); ?>.
      </p>

       <div class="ui-corner-all safetext-rounded-corners">
              <div class="ui-bar ui-bar-a">
                <h3><?php echo $this->t('Send Email'); ?></h3>
              </div>
              
              <div class="ui-body ui-body-b">
                    <form class="safetext-sendpassword-form">
                        <ul data-role="listview" data-inset="true" data-theme="a">
                            
                            <li class="ui-field-contain">
							    <label for="email"><?php echo $this->t('Email'); ?>:</label>
							    <input type="text" name="email" data-clear-btn="true">
							</li>
                                                               
                            <li class="ui-body ui-body-b">
                                <fieldset class="ui-grid-a">
                                        <button type="button" class="ui-btn ui-corner-all ui-btn-a safetext-send-button"><?php echo $this->t('Submit'); ?></button>
                                </fieldset>
                            </li>
                        </ul>
                    </form>
              </div>
        </div>
	    <br /><br />
	    </div><!-- /content -->
	    
	    
	<?php echo $this->render('front/_footer.phtml'); ?>
		
</div> <!--/page-->